### ISSUE TITLE
Error : Error Network

### ISSUE THREAD

**Issue by SadiqMohamed** [instamed/healthcare-payments-blockchain#11]
hi,
thank you for this interesting project, everything looks perfect but when I want to use the demo I got the errors below after running the server, on this page "localhost:8080/provider"
```
server: calling couch to 5084 in db ch1_financial
server: { Error: Document is not found
server:     at _requestWrapped.then (/home/blockchain/healthcare-payments-blockchain/node_modules/node-couchdb/dist/es2015.js:180:23)
server:     at <anonymous>
server:     at process._tickCallback (internal/process/next_tick.js:188:7)
server:   code: 'EDOCMISSING',
server:   body: { error: 'not_found', reason: 'missing' } }
```
and this error in the browser:
```
app.de3c1254.js:1 TypeError: ns.GetCommandSrc is not a function
    at GetCommandUrl (main.js?attr=-uBnolNbMXFJ7EeWJwZINMXn4wv6fLahWUr2K3LgrbThCnVAipsP4XlFuAkDroxbm5BgD60pkDi19TnpvjwiYA:988)
    at XMLHttpRequest.window.XMLHttpRequest.open (main.js?attr=-uBnolNbMXFJ7EeWJwZINMXn4wv6fLahWUr2K3LgrbThCnVAipsP4XlFuAkDroxbm5BgD60pkDi19TnpvjwiYA:1023)
    at chunk-vendors.82dcf0ff.js:12
    at new Promise (<anonymous>)
    at e.exports (chunk-vendors.82dcf0ff.js:12)
    at e.exports (chunk-vendors.82dcf0ff.js:7)
```
when I send data I got this error : 
```
POST http://localhost:8080/api/patient?user=provider net::ERR_CONNECTION_REFUSED
```

**Comment by instameddevelopment** [comment]
Hi @SadiqMohamed. I run the application but there seems to be working. Maybe you skipped the `npm run views:install` command after running the postman requests? Feel free to re-open if you continue having problems.
